---
title: "Basic Statistics"
author: Harald Puhr
date: "April 1, 2025"
---

[Data Source](https://github.com/ha-pu/data_files/tree/main#user-knowledge-modeling-dataset)

# Load tidyverse package and data
```{r}
library(tidyverse)
```

```{r}
df <- read_csv("https://raw.githubusercontent.com/ha-pu/data_files/refs/heads/main/1-user_knowledge.csv")
df$UNS <- factor(df$UNS, levels = c("Very Low", "Low", "Middle", "High"))
```

# Get frequency of skill levels

```{r}
count(df, UNS)
```

# Analyze study effort by skill level

```{r}
summarise(
    df,
    n = n(),
    across(c(STG, SCG, STR, LPR, PEG), mean),
    .by = UNS
) %>%
    arrange(UNS)
```

# Distribution of study effort

```{r}
df %>%
    pivot_longer(
        cols = c(STG, SCG, STR, LPR, PEG),
        names_to = "knowledge",
        values_to = "value"
    ) %>%
    ggplot() +
    geom_histogram(aes(value)) +
    facet_wrap(~knowledge) +
    theme_bw()
```

# Boxplot of study effort by skill level

```{r}
df %>%
    pivot_longer(
        cols = c(STG, SCG, STR, LPR, PEG),
        names_to = "knowledge",
        values_to = "value"
    ) %>%
    ggplot() +
    geom_boxplot(aes(x = UNS, y = value)) +
    facet_wrap(~knowledge) +
    theme_bw()
```

# Correlation between study effort variables

```{r}
df %>%
    select(-UNS) %>%
    cor()
```

```{r}
df %>%
    select(-UNS) %>%
    cor() %>%
    as_tibble(rownames = "Var1") %>%
    pivot_longer(
        cols = -Var1,
        names_to = "Var2",
        values_to = "Correlation"
    ) %>%
    ggplot() +
    geom_tile(aes(x = Var1, y = Var2, fill = Correlation))
```

# Test the statistical signficance of differences between skill levels

```{r}
df <- mutate(
    df,
    upper_half = UNS %in% c("High", "Middle"),
    top = UNS == "High"
)
```

```{r}
t.test(STG ~ upper_half, data = df)
```

```{r}
t.test(STG ~ top, data = df)
```

```{r}
out <- aov(STG ~ UNS, data = df)
summary(out)
```
